# Generated by Django 4.1.5 on 2023-01-07 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CmsSlider',
            new_name='Slider',
        ),
    ]
