# Generated by Django 4.1.5 on 2023-01-07 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_rename_cmsslider_slider'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='cms_css',
            field=models.CharField(default='-', max_length=200, null=True, verbose_name='CSS class'),
        ),
    ]
