# Generated by Django 4.1.5 on 2023-01-07 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_slider_cms_css'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Slider',
            new_name='CmsSlider',
        ),
    ]
